### ISSUE TITLE
InvalidOperationException: Cannot find the fallback endpoint specified by route values: { page: /_Host, area: }.

### ISSUE THREAD

**Issue by vobonyo** [ADefWebserver/ADefHelpDesk#4]
I downloaded the latest code that you have but I’m getting the attached error every time I try to run it. The fixes I have found online are just not working. Please help. Thanks.

Error:

An unhandled exception occurred while processing the request.
InvalidOperationException: Cannot find the fallback endpoint specified by route values: { page: /_Host, area: }.
Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.DynamicPageEndpointMatcherPolicy.ApplyAsync(HttpContext httpContext, CandidateSet candidates)

![FallbackEndPointError](https://user-images.githubusercontent.com/25969103/147800671-da9be4e9-33e4-4061-95f1-98b503ea659c.PNG)

**Comment by ADefWebserver** [comment]
If this is for the Blazor version, it is not complete yet. The database has to properly set up for it to work, and the installer code is currently not working correctly. Hopefully this will be working in February.

**Comment by ADefWebserver** [comment]
ADefHelpDesk Blazor version is now complete.
